### ISSUE TITLE
Add Users

### ISSUE THREAD

**Issue by wu-jeffrey** [wu-jeffrey/ece356-project#2]
# Goal

- add user accounts and signup, login, logout capabilities
- users can either be an `Admin` or an `Investor`
- `Admin`s can CRUD on stocks
- `Investor`s can add stocks to their watchlist

## TODOs
- [x] Create table for `Users`, with `role, email, password, etc.`
- [x] CRUD APIs for users
- [x] Need to gate users from accessing watchlists that aren't theirs, should probably use some sort of token, maybe JWT? Or maybe just use a primitive token or something

**Comment by wu-jeffrey** [comment]
resolved: https://github.com/wu-jeffrey/ece356-project/pull/8

did not implement watchlists yet
