### ISSUE TITLE
Create views

### ISSUE THREAD

**Issue by wu-jeffrey** [wu-jeffrey/ece356-project#3]
# Goals

I think we should create a "view" for each API
this is probably stupid in practice because an ORM should handle this, and changing the backend API is now coupled with a DB change but I think we should use `SQL views` to maybe differentiate different data available to different types of users. 

## TODO: 
- [x] someone edit this please :P

**Comment by wu-jeffrey** [comment]
@eunseochoi created views for HomePage to have multiple select statements so next steps are:

- [x] Hook home page up with backend & DB: https://github.com/wu-jeffrey/ece356-project/issues/19
- [x] reconfig admins to instead be a bool for institution: https://github.com/wu-jeffrey/ece356-project/issues/12
     - [x] utilize the institution view in the DB call for the `annualReport`

**Comment by wu-jeffrey** [comment]
3 views created & used in client app
