### ISSUE TITLE
Watchlists - Allow users to "watch" stocks

### ISSUE THREAD

**Issue by wu-jeffrey** [wu-jeffrey/ece356-project#5]
# Goals
Investors should be able to add/remove stocks from their watchlist.
add from the companies index page
remove from homepage

## TODO
- [ ] Create Watchlists Table
- [ ] CRUD to add/remove stocks from watchlist (We'll limit each user to having a single watchlist (for scope), so each user has one watchlist)
- [ ] Make sure IDOR is not a problem, we should be hooking into the auth cookie to get the correct user watchlist
